language: ruby
rvm:
- 2.6

cache: bundler # speed up

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./.travis.build.sh ./_config_$TRAVIS_BRANCH.yml

# branch whitelist, only for GitHub Pages
branches:
  only:
   - master
   - prod
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

#env:
#  global:
#  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

addons:
  ssh_known_hosts: prod.cmlteam.com

before_deploy:
- openssl aes-256-cbc -K $encrypted_10e2a48999a5_key -iv $encrypted_10e2a48999a5_iv
  -in deploy_rsa.enc
  -out /tmp/deploy_rsa -d
- chmod 600 /tmp/deploy_rsa

#deploy:
#  provider: pages
#  skip_cleanup: true
#  repo: xonixx/xonixx.github.io
#  target_branch: master
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  local_dir: site
#  on:
#    branch: master

deploy:
  # Deploy latest approved code to TEST
  - provider: script
    skip_cleanup: true
    script: ./.travis.deploy_master.sh
    on:
      branch: master

  # Deploy stable version to PROD
  - provider: script
    skip_cleanup: true
    script: ./.travis.deploy_prod.sh
    on:
      branch: prod
