language: ruby
rvm:
- 2.3.4

cache: bundler # speed up

#before_script:
# - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./cibuild.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
   - master
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

#env:
#  global:
#  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: pages
  skip_cleanup: true
  repo: xonixx/xonixx.github.io
  target_branch: master
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: site
  on:
    branch: master