language: ruby
rvm:
- 2.3.4

cache: bundler # speed up

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
- bundle exec jekyll build
#- mv _site site # looks like deploy phase doesn't like underscores
#- echo www.cmlteam.com > site/CNAME # custom domain
- rm _site/*.sh _site/*.enc || true

# branch whitelist, only for GitHub Pages
branches:
  only:
   - master
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

#env:
#  global:
#  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

addons:
  ssh_known_hosts: prod.cmlteam.com

before_deploy:
- openssl aes-256-cbc -K $encrypted_10e2a48999a5_key -iv $encrypted_10e2a48999a5_iv
  -in deploy_rsa.enc
  -out /tmp/deploy_rsa -d
- chmod 600 /tmp/deploy_rsa

#deploy:
#  provider: pages
#  skip_cleanup: true
#  repo: xonixx/xonixx.github.io
#  target_branch: master
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  local_dir: site
#  on:
#    branch: master

deploy:
  provider: script
  skip_cleanup: true
  script:
  - ssh -i /tmp/deploy_rsa apps1@prod.cmlteam.com "(cd ; rm -rf www.cmlteam.com ; mkdir www.cmlteam.com) >> /tmp/.deploy 2>&1"
  - cd _site ; scp -i /tmp/deploy_rsa -C -r * apps1@prod.cmlteam.com:~/www.cmlteam.com