url: https://www.cmlteam.com
baseurl:
resources_server_url:

# Site settings
short-name: CML
full-name: CML Team
email: info@cmlteam.com
description: "CML Team, Full-Stack Development, IT-Consulting for Startups and Enterprises, Blockchain"

# Team names, titles and social links
people:
- name: Oleksandr Shchetynin
  pic: img/team/1.jpg
  position: CVO & CO-FOUNDER
  description: Worked in companies of different sizes, from successful startups to Fortune 500 companies, performing mission-critical responsibilities, developing and implementing high-tech IT solutions for a variety of industries.
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/justrocknrolla
#    - title: stack-overflow
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/shchetynin/

- name: Vladyslav Sikach
  pic: img/team/2.jpg
  position: CEO & CO-FOUNDER
  description: Has extensive business development and quantitative analytics experience from his work as the Head of Process Development in one of CIS’s leaders in debt collection to a Business Architect in a large Asian bank.
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/SikachV
#    - title: google-plus
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/sikach/

- name: Volodymyr Gubarkov
  pic: img/team/3.jpg
  position: CTO & CO-FOUNDER
  description: Focused primarily on backend development and infrastructure setup. Possesses solid object oriented systems design and implementation, system architectures development experience.
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/volodymyr.gubarkov
    - title: linkedin
      url: https://www.linkedin.com/in/gubarkovv/

- name: Basil Gorin
  pic: img/team/4.jpg
  position: CO-FOUNDER
  description: Focused primarily on smart contracts development, payments processing and security. Has strong experience with e-commerce software development and distributed storage systems.
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: https://www.facebook.com/basil.gorin
#    - title: google-plus
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/gorin/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url:
  - title: linkedin
    url: https://www.linkedin.com/company/18045280/
  - title: github
    url: https://github.com/CMLTeam
  - title: instagram
    url: https://www.instagram.com/cmlteam/
  - title: youtube
    url: https://www.youtube.com/channel/UCQv9UK-79-XoHftaA2j1nZw
  - title: medium
    url: https://medium.com/cmlteam

# Postal address (add as many lines as necessary)
address: Suite 6, 5 Percy Street, London, Fitzrovia, United Kingdom, W1T 1DG
address2: 3 Mala Zhytomyrska St, Kyiv, 01001

# Build settings
markdown: kramdown
permalink: pretty
