url: https://www.cmlteam.com
baseurl:

# Site settings
short-name: CML
full-name: CML Team
email: info@cmlteam.com
description: "CML Team, Full-Stack Development, IT-Consulting for Startups and Enterprises, Blockchain"

# Team names, titles and social links
people:
- name: Oleksandr Shchetynin
  pic: 1
  position: Tech lead and software developer with a wide experience in a successful travel startup as well as 500 Fortune companies. Traveled across both Americas, Europe and Asia
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/justrocknrolla
#    - title: stack-overflow
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/shchetynin/

- name: Vladislav Sikach
  pic: 2
  position: Extensive business development experience from Head of Process Development in debt collection to Business Architect in large Asian bank. Visited 40+ countries and not planning to stop
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/Vladislav.Sikach
#    - title: google-plus
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/vladislavsikach/

- name: Volodymyr Gubarkov
  pic: 3
  position: Former key developer and currently a shareholder of a successful startup called Alice that raised recently $30 Mln
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/volodymyr.gubarkov
    - title: linkedin
      url: https://www.linkedin.com/in/vladimirgubarkov/

- name: Basil Gorin
  pic: 4
  position: Technical designer. Strong experience with blockchain, security, e-commerce software development and distributed storage systems.
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: https://www.facebook.com/basil.gorin
#    - title: google-plus
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/gorin/

#- name: Oleksii Potapenko
#  pic: 5
#  position: Data Scientist
#  social:
##    - title: twitter
##      url: #
#    - title: facebook
#      url: https://www.facebook.com/oleksii.potapenko
##    - title: google-plus
##      url: #
#    - title: linkedin
#      url: https://www.linkedin.com/in/oleksii-potapenko-23413982/
#
#- name: Sergey Sviridenko
#  pic: 7
#  position: Data Scientist
#  social:
##    - title: twitter
##      url: #
#    - title: facebook
#      url: https://www.facebook.com/sergey.sviridenko.311
##    - title: google-plus
##      url: #
#    - title: linkedin
#      url: https://www.linkedin.com/in/sergeysviridenko/
#
#- name: Denys Nienov
#  pic: 6
#  position: Legal Consultant
#  social:
##    - title: twitter
##      url: #
#    - title: facebook
#      url: https://www.facebook.com/den.nenov
##    - title: google-plus
##      url: #
#    - title: linkedin
#      url: https://www.linkedin.com/in/%D0%B4%D0%B5%D0%BD%D0%B8%D1%81-%D0%BD%D0%B5%D0%BD%D0%BE%D0%B2-31481978/
#
#- name: Nikita Malenko
#  pic: 8
#  position: Software Engineer
#  social:
##    - title: twitter
##      url: #
#    - title: facebook
#      url: https://www.facebook.com/malenik1
##    - title: google-plus
##      url: #
#    - title: linkedin
#      url: https://www.linkedin.com/in/nikita-malenko-b37bb5139/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url:
  - title: linkedin
    url: https://www.linkedin.com/company/18045280/
  - title: github
    url: https://github.com/CMLTeam
  - title: instagram
    url: https://www.instagram.com/cmlteam/
  - title: youtube
    url: https://www.youtube.com/channel/UCQv9UK-79-XoHftaA2j1nZw

# Postal address (add as many lines as necessary)
address: 10 Mala Zhytomyrska St, Kyiv, 01001

# Build settings
markdown: kramdown
permalink: pretty