url: https://www.cmlteam.com
baseurl:

# Site settings
short-name: CML
full-name: CML Team
email: info@cmlteam.com
description: "CML Team, Full-Stack Development, IT-Consulting for Startups and Enterprises, Blockchain"

# Team names, titles and social links
people:
- name: Oleksandr Shchetynin
  pic: 1
  position: CVO and co-founder. Worked in companies of different sizes, from small startups to Fortune 500 companies, performing mission-critical responsibilities for variety of industries.
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/justrocknrolla
#    - title: stack-overflow
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/shchetynin/

- name: Vladislav Sikach
  pic: 2
  position: CEO and co-founder. Has extensive business development and quantitative analytics experience from Head of Process Development in one of CIS’s leaders in debt collection to Business Architect in large Asian bank.
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/Vladislav.Sikach
#    - title: google-plus
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/vladislavsikach/

- name: Volodymyr Gubarkov
  pic: 3
  position: CTO and co-founder. Focused primarily on backend development and infrastructure setup. He possess solid object oriented systems design and implementation, system architectures development experience.
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/volodymyr.gubarkov
    - title: linkedin
      url: https://www.linkedin.com/in/vladimirgubarkov/

- name: Basil Gorin
  pic: 4
  position: Co-founder. Focused primarily on smart contracts development, payments processing and security. He has strong experience with e-commerce software development and distributed storage systems.
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: https://www.facebook.com/basil.gorin
#    - title: google-plus
#      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/gorin/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url:
  - title: linkedin
    url: https://www.linkedin.com/company/18045280/
  - title: github
    url: https://github.com/CMLTeam
  - title: instagram
    url: https://www.instagram.com/cmlteam/
  - title: youtube
    url: https://www.youtube.com/channel/UCQv9UK-79-XoHftaA2j1nZw
  - title: medium
    url: https://medium.com/cmlteam

# Postal address (add as many lines as necessary)
address: 10 Mala Zhytomyrska St, Kyiv, 01001

# Build settings
markdown: kramdown
permalink: pretty