on: 
  push:
    branches:
      - master
      - prod
# TODO decide what to do with other branches than master/prod. Now the build will just fail (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters)

name: "Deploy"
jobs:
  deploy:
    name: "Deploys the site"
    runs-on: ubuntu-20.04
    env:
      DEPLOY_RSA_KEY: ${{ secrets.DEPLOY_RSA_KEY }} # https://damienaicheh.github.io/github/actions/2021/04/15/environment-variables-secrets-github-actions-en.html
    steps:
      - uses: actions/checkout@v2

#      - uses: actions/cache@v2
#        id: cache-soft
#        with:
#          path: soft
#          key: ${{ matrix.os }}-soft--all-1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.94.0
        with:
          ruby-version: 2.6
          bundler-cache: true # https://www.jessesquires.com/blog/2021/08/23/caching-bundler-on-github-actions/

      - name: "deploy"
        run: |
          set -e
          
          # https://docs.github.com/en/actions/learn-github-actions/environment-variables
          #echo "branch=$GITHUB_REF_NAME"
          
          ./makesure deployed